### ISSUE TITLE
[MSHARED-1289] Deprecate maven-shared-utils

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shared-utils#332]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** opened **[MSHARED-1289](https://issues.apache.org/jira/browse/MSHARED-1289?redirect=false)** and commented

As discussed in https://lists.apache.org/thread/9wkmo1cfq7hx6qwo2xp070rkdz1w5myp this library never became successor of plexus-utils and therefore is less maintained. Instead of maintaining two libraries we should deprecated Maven Shared Utils and recommend using plain JDK API where possible or fall back to either plexus-utils or other  well known third party libraries.

---

**Issue Links:**
- [MSHARED-1269](https://issues.apache.org/jira/browse/MSHARED-1269) Deprecate maven-shared-utils
 (_**"duplicates"**_)

**Remote Links:**
- [GitHub Pull Request #165
](https://github.com/apache/maven-shared-utils/pull/165)

**Comment by slachiewicz** [comment]
Housekeeping note: the `feature/deprecation` branch that carried the work for this issue has been deleted from the repository.

It deprecated the library in favour of `org.codehaus.plexus.util.*`, which is the opposite of the direction settled here and on [#165](https://github.com/apache/maven-shared-utils/issues/165) and [#311](https://github.com/apache/maven-shared-utils/issues/311) -- all three closed as not planned. The branch was last touched in July 2023 and had fallen 69 commits behind `master`. 3.5.0 does deprecate a large part of the API, but pointing at the JDK and `commons-lang3`, never at Plexus.

Nothing is lost: the commit is `fe66f994fc61b6639102d1259775145a89738d7b` and can be restored with `git checkout -b feature/deprecation fe66f99` by anyone who wants it back.

*This comment was created with AI assistance.*
